#!/bin/bash
set -e  # Exit on any error

# ------------------------
# Colors for output
# ------------------------
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# ------------------------
# Variables
# ------------------------
STACK_NAME="idma-deployment-stack"
ENVIRONMENT="dev"
REGION="us-east-1"
ACCOUNT_ID="$(aws sts get-caller-identity --query Account --output text)"
IDMATAGNAME="idmaresource"
MODEL_ARN=arn:aws:bedrock:${REGION}:${ACCOUNT_ID}:inference-profile/us.anthropic.claude-sonnet-5

# Basic auth username for the Amplify-hosted frontend. The matching password is
# generated by CloudFormation and stored in Secrets Manager.
BASIC_AUTH_USERNAME="idmaadmin"

# S3 bucket names
KB_BUCKET="idma-kb-${ACCOUNT_ID}-${REGION}-${ENVIRONMENT}"
LAMBDA_BUCKET="idma-lambda-${ACCOUNT_ID}-${REGION}-${ENVIRONMENT}"
FRONTEND_BUCKET="idma-react-${ACCOUNT_ID}-${REGION}-${ENVIRONMENT}"

# ------------------------
# Helper Functions
# ------------------------
print_message() {
    local color="$1"
    local message="$2"
    echo -e "${color}${message}${NC}"
}

create_bucket_if_not_exists() {
    local bucket_name="$1"
    
    print_message "${YELLOW}" "Creating S3 bucket: ${bucket_name}"
    if ! aws s3api head-bucket --bucket "${bucket_name}" 2>/dev/null; then
        aws s3 mb "s3://${bucket_name}" --region "${REGION}"
        print_message "${GREEN}" "Bucket created successfully"

        aws s3api put-bucket-tagging --bucket "${bucket_name}" --tagging "TagSet=[{Key=Environment,Value=${ENVIRONMENT}},{Key=Application,Value=${IDMATAGNAME}}]"
        print_message "${GREEN}" "Tags added successfully"

    else
        print_message "${YELLOW}" "Bucket already exists"
        aws s3api put-bucket-tagging --bucket "${bucket_name}" --tagging "TagSet=[{Key=Environment,Value=${ENVIRONMENT}},{Key=Application,Value=${IDMATAGNAME}}]"
        print_message "${GREEN}" "Tags updated successfully"        
    fi
}

update_env_var() {
    local key="$1"
    local value="$2"
    local env_file="../frontend/.env"

    mkdir -p "$(dirname "${env_file}")"
    touch "${env_file}"

    if grep -q "^${key}=" "${env_file}"; then
        if [[ "${OSTYPE}" == "darwin"* ]]; then
            sed -i '' "s|^${key}=.*|${key}=${value}|" "${env_file}"
        else
            sed -i "s|^${key}=.*|${key}=${value}|" "${env_file}"
        fi
    else
        echo "${key}=${value}" >> "${env_file}"
    fi
    print_message "${GREEN}" "Updated ${key} in .env file"
}

check_command() {
    if ! command -v "$1" &> /dev/null; then
        print_message "${RED}" "Error: $1 is not installed. Please install it first."
        exit 1
    fi
}

# ------------------------
# Prerequisites Check
# ------------------------
print_message "${YELLOW}" "Checking prerequisites..."
check_command aws
check_command jq
check_command zip
check_command npm

# ------------------------
# Create S3 Buckets
# ------------------------
print_message "${YELLOW}" "Creating required S3 buckets..."
create_bucket_if_not_exists "${KB_BUCKET}"
create_bucket_if_not_exists "${LAMBDA_BUCKET}"
create_bucket_if_not_exists "${FRONTEND_BUCKET}"

# ------------------------
# Setup Knowledge Base
# ------------------------
print_message "${YELLOW}" "Setting up Knowledge Base..."
export KB_BUCKET="${KB_BUCKET}"
export AWS_REGION_KB="${REGION}"

print_message "${YELLOW}" "Updating environment variables..."
update_env_var "REACT_APP_S3_BUCKET" "${KB_BUCKET}"
update_env_var "AWS_REGION" "${REGION}"
update_env_var "REACT_APP_MODEL_ARN" "${MODEL_ARN}"

print_message "${YELLOW}" "Copying knowledge base files..."
if [ -f "context_data.jsonl" ]; then
    aws s3 cp context_data.jsonl "s3://${KB_BUCKET}/"
    print_message "${GREEN}" "Uploaded context_data.jsonl"
fi

if [ -d "../knowledge_base" ]; then
    print_message "${YELLOW}" "Copying knowledge_base directory contents..."
    find ../knowledge_base -type f | while read -r file; do
        target_path="$(echo "${file}" | sed 's|../knowledge_base/||')"
        target_path="$(echo "${target_path}" | sed -e 's/ //g')"
        echo "${target_path}"
        aws s3 cp "${file}" "s3://${KB_BUCKET}/knowledge_base/${target_path}"
    done
    print_message "${GREEN}" "Knowledge base files uploaded successfully"
fi


# ------------------------
# Package and Upload Lambda Functions
# ------------------------
print_message "${YELLOW}" "Setting up Lambda functions..."

print_message "${YELLOW}" "Uploading Lambda layer..."
aws s3 cp ../backend/lambda-layer/lambda-idma-layer.zip "s3://${LAMBDA_BUCKET}/layers/layer.zip"
aws s3 cp ../backend/lambda-layer/vectorLayer.zip "s3://${LAMBDA_BUCKET}/layers/vectorLayer.zip"
mkdir -p temp_lambda

package_lambda() {
    local function_name="$1"
    local source_dir="$2"
    local zip_name="$3"

    print_message "${YELLOW}" "Processing ${function_name}..."
    cd "${source_dir}" || exit 1
    zip -r "../../../deployment/temp_lambda/${zip_name}" .
    cd ../../../deployment || exit 1
    aws s3 cp "temp_lambda/${zip_name}" "s3://${LAMBDA_BUCKET}/lambda/${zip_name}"
    print_message "${GREEN}" "${function_name} packaged and uploaded successfully"
}

package_lambda "bot handler" "../backend/functions/bot" "idma-bot-handler.zip"
package_lambda "database migration" "../backend/functions/DatabaseMigration" "database-migration.zip"
package_lambda "analytics handler" "../backend/functions/analytics" "analytics_handler.zip"
package_lambda "modern strategy" "../backend/functions/modern-data-strategy" "modern-data-strategy.zip"

print_message "${YELLOW}" "Creating Knowledge Base..."

# ------------------------
# Deploy CloudFormation Stack
# ------------------------
print_message "${YELLOW}" "Deploying CloudFormation stack..."

RANDOM_PREFIX="$(openssl rand -hex 4)"
print_message "${YELLOW}" "Using random prefix: ${RANDOM_PREFIX}"

aws cloudformation deploy \
  --template-file unified-template.yaml \
  --stack-name "${STACK_NAME}" \
  --parameter-overrides \
    "Environment=${ENVIRONMENT}" \
    "BaseStackName=${STACK_NAME}" \
    "KnowledgeBaseBucketName=${KB_BUCKET}" \
    "LambdaCodeBucketName=${LAMBDA_BUCKET}" \
    "FrontendBucket=${FRONTEND_BUCKET}" \
    "RandomPrefix=${RANDOM_PREFIX}" \
    "BasicAuthUsername=${BASIC_AUTH_USERNAME}" \
  --capabilities CAPABILITY_NAMED_IAM \
  --region "${REGION}" \
  --s3-bucket "${LAMBDA_BUCKET}"

# Then get IDs and run DataSync
print_message "${YELLOW}" "Getting Knowledge Base and Data Source IDs..."
KBID="$(aws cloudformation describe-stacks \
    --stack-name "${STACK_NAME}" \
    --region "${REGION}" \
    --query 'Stacks[0].Outputs[?OutputKey==`KnowledgeBaseId`].OutputValue' \
    --output text)"

DSID="$(aws cloudformation describe-stacks \
    --stack-name "${STACK_NAME}" \
    --region "${REGION}" \
    --query 'Stacks[0].Outputs[?OutputKey==`DataSourceId`].OutputValue' \
    --output text)"

if [ -n "${KBID}" ] && [ -n "${DSID}" ]; then
    print_message "${YELLOW}" "Starting Data Source Sync..."
    python3 DataSync.py "${KBID}" "${DSID}" "${REGION}"
else
    print_message "${RED}" "Failed to retrieve Knowledge Base ID or Data Source ID"
    print_message "${YELLOW}" "KBID: ${KBID}"
    print_message "${YELLOW}" "DSID: ${DSID}"
    exit 1
fi
# # ------------------------
# # Build and Deploy Frontend
# # ------------------------

print_message "${YELLOW}" "Getting API Gateway endpoint..."
API_ENDPOINT="$(aws cloudformation describe-stacks \
    --stack-name "${STACK_NAME}" \
    --region "${REGION}" \
    --query 'Stacks[0].Outputs[?OutputKey==`ApiEndpoint`].OutputValue' \
    --output text)"

if [ -n "${API_ENDPOINT}" ]; then
    print_message "${YELLOW}" "Updating frontend environment with API endpoint..."
    update_env_var "REACT_APP_API_URL" "${API_ENDPOINT}"
fi

print_message "${YELLOW}" "Building frontend application..."
cd ../frontend || exit 1
npm install
npm run build

print_message "${YELLOW}" "Uploading React build to S3..."
if ! aws s3 sync build/ "s3://${FRONTEND_BUCKET}/" --delete; then
    print_message "${RED}" "Error: Failed to upload frontend build to S3"
    exit 1
fi
cd ../deployment || exit 1

# ------------------------
# Deploy to Amplify
# ------------------------
AMPLIFY_APP_ID="$(aws cloudformation describe-stacks \
    --stack-name "${STACK_NAME}" \
    --region "${REGION}" \
    --query "Stacks[0].Outputs[?OutputKey=='AmplifyAppId'].OutputValue" \
    --output text)"
BRANCH_NAME="main"
LOCAL_BUILD_DIR="../frontend/build"  # :point_right: Local build directory path
if [ -z "${AMPLIFY_APP_ID}" ]; then
    print_message "${RED}" "Error: Could not retrieve Amplify App ID."
    exit 1
fi
print_message "${GREEN}" "Amplify App ID: ${AMPLIFY_APP_ID}"
# Create a temporary directory
TEMP_DIR="$(mktemp -d)"
ZIP_FILE="${TEMP_DIR}/app.zip"
# Copy contents *inside* build/ to temp dir root
print_message "${YELLOW}" "Copying contents of '${LOCAL_BUILD_DIR}' to temp directory..."
cp -r "${LOCAL_BUILD_DIR}/." "${TEMP_DIR}/"
# Navigate to the temp dir and zip everything there (not the parent 'build' folder)
cd "${TEMP_DIR}" || exit 1
print_message "${YELLOW}" "Zipping the application files (excluding outer 'build' folder)..."
zip -r "${ZIP_FILE}" . > /dev/null
# Create deployment and retrieve upload URLs
print_message "${YELLOW}" "Creating Amplify deployment..."
DEPLOYMENT_RESPONSE="$(aws amplify create-deployment \
    --app-id "${AMPLIFY_APP_ID}" \
    --region "${REGION}" \
    --branch-name "${BRANCH_NAME}" \
    --output json)"
DEPLOYMENT_ID="$(echo "${DEPLOYMENT_RESPONSE}" | jq -r '.jobId')"
ZIP_UPLOAD_URL="$(echo "${DEPLOYMENT_RESPONSE}" | jq -r '.zipUploadUrl')"
if [ -z "${DEPLOYMENT_ID}" ] || [ -z "${ZIP_UPLOAD_URL}" ]; then
    print_message "${RED}" "Error: Failed to retrieve deployment ID or upload URL."
    rm -rf "${TEMP_DIR}"
    exit 1
fi
print_message "${GREEN}" "Deployment ID: ${DEPLOYMENT_ID}"
# Upload the zip file to the provided URL
print_message "${YELLOW}" "Uploading the zip file to Amplify..."
curl -T "${ZIP_FILE}" "${ZIP_UPLOAD_URL}"
# Start the deployment
print_message "${YELLOW}" "Starting the deployment..."
aws amplify start-deployment \
    --app-id "${AMPLIFY_APP_ID}" \
    --region "${REGION}" \
    --branch-name "${BRANCH_NAME}" \
    --job-id "${DEPLOYMENT_ID}"
# Monitor deployment status
print_message "${YELLOW}" "Monitoring deployment status..."
while true; do
    STATUS="$(aws amplify get-job \
        --app-id "${AMPLIFY_APP_ID}" \
        --branch-name "${BRANCH_NAME}" \
        --job-id "${DEPLOYMENT_ID}" \
        --region "${REGION}" \
        --query 'job.summary.status' \
        --output text)"
    print_message "${YELLOW}" "Current status: ${STATUS}"
    if [ "${STATUS}" = "SUCCEED" ]; then
        print_message "${GREEN}" "Deployment completed successfully!"
        break
    elif [ "${STATUS}" = "FAILED" ]; then
        print_message "${RED}" "Deployment failed!"
        rm -rf "${TEMP_DIR}"
        exit 1
    fi
    sleep 10
done

# ------------------------
# Cleanup
# ------------------------
print_message "${YELLOW}" "Cleaning up temporary files..."
rm -rf "${TEMP_DIR}"
rm -rf temp_lambda

# ------------------------
# Display Final Information
# ------------------------
print_message "${GREEN}" "\nDeployment Complete!"
print_message "${GREEN}" "================================"
print_message "${GREEN}" "API Endpoint: ${API_ENDPOINT}"
print_message "${GREEN}" "Frontend Bucket: ${FRONTEND_BUCKET}"
print_message "${GREEN}" "Knowledge Base Bucket: ${KB_BUCKET}"

AMPLIFY_DOMAIN="$(aws cloudformation describe-stacks \
    --stack-name "${STACK_NAME}" \
    --region "${REGION}" \
    --query 'Stacks[0].Outputs[?OutputKey==`AmplifyDomain`].OutputValue' \
    --output text)"

print_message "${GREEN}" "Amplify Domain: ${AMPLIFY_DOMAIN}"
print_message "${GREEN}" "Amplify Console URL: https://${REGION}.console.aws.amazon.com/amplify/home?region=${REGION}#/${AMPLIFY_APP_ID}"

# The site is protected by basic auth. The password is intentionally NOT printed
# here so it stays out of terminal scrollback and CI logs.
BASIC_AUTH_SECRET_ARN="$(aws cloudformation describe-stacks \
    --stack-name "${STACK_NAME}" \
    --region "${REGION}" \
    --query 'Stacks[0].Outputs[?OutputKey==`BasicAuthSecretArn`].OutputValue' \
    --output text)"

print_message "${GREEN}" "--------------------------------"
print_message "${GREEN}" "Basic auth username: ${BASIC_AUTH_USERNAME}"
print_message "${GREEN}" "Retrieve the password with:"
print_message "${GREEN}" "  aws secretsmanager get-secret-value --secret-id ${BASIC_AUTH_SECRET_ARN} --region ${REGION} --query SecretString --output text | jq -r .password"
print_message "${GREEN}" "================================"