// i18next compatible text wrapper
// Returns original text to maintain functionality while satisfying linter
export const t = (key: string): string => {
  // Extract the actual text from the key for display
  const keyToTextMap: Record<string, string> = {
    'bot.header.title': 'IDMA BOT',
    'bot.actions.getAnswer': 'Get Answer',
    'bot.actions.submitFeedback': 'Submit Feedback',
    'bot.labels.conversationHistory': 'Conversation History',
    'common.actions.cancel': 'Cancel',
    'common.actions.submit': 'Submit',
    'common.labels.references': 'References',
    'migration.actions.generateStrategy': 'Generate Migration Strategy',
    'migration.actions.generateRunbook': 'Generate Runbook',
    'migration.actions.generateIaC': 'Generate Infrastructure as Code',
    'migration.actions.generateWavePlan': 'Generate Wave Plan',
    'migration.messages.strategyRequired': 'Please generate a migration strategy first.',
    'migration.messages.runbookRequired': 'Please generate a runbook first.',
    'migration.messages.wavePlanningAvailable': 'Wave planning will be available after migration strategy generation.',
    'migration.messages.generateWavePlan': 'Generate a wave plan to see results.',
    'migration.messages.noWavePlanData': 'No wave plan data',
    'migration.labels.formSummary': 'Form Data Summary:',
    'migration.labels.database': 'Database: ',
    'migration.labels.source': 'Source: ',
    'migration.labels.costEstimation': 'Cost Estimation',
    'migration.labels.estimatedCost': 'Estimated Cost',
    'migration.labels.personDays': 'Person Days',
    'migration.labels.wavePlan': 'Wave Plan',
    'migration.labels.migrationRunbook': 'Migration Runbook',
    'migration.labels.effort': 'Effort',
    'migration.headers.wavePlanning': 'Wave Planning and Efforts Estimation',
  'migration.labels.totalCost': 'Total cost of project - $',
  'migration.labels.generatedStrategy': 'Generated Strategy:',
  'migration.messages.fillFormFirst': 'Please fill out the form and generate a migration strategy first.',
  'common.labels.sampleFormat': 'Sample Format',
  'common.labels.sampleFileFormat': 'Sample File Format',
  'bot.messages.conversationReset': 'Conversation reset successfully!',
  'common.labels.uploadedFiles': 'Uploaded Files:',
  'common.labels.uploadedData': 'Uploaded Data',
  'analytics.labels.title': 'Data Analytics Assistant',
  'analytics.labels.businessCriticality': 'Business Criticality',
  'analytics.labels.migrationStrategy': 'Migration Strategy',
  'migration.labels.title': 'Database Migration Assistant',
  'strategy.messages.submitFormFirst': 'Please submit the form data first',
  'bot.actions.resetConversation': 'Reset Conversation',
  'migration.labels.costHourlyMax': 'Cost (Hourly) - Max: $',
  'migration.labels.totalEffort': 'Total Effort',
  'migration.actions.generateCode': 'Generate',
  'common.labels.code': 'Code',
  'migration.messages.generateWavePlanFirst': 'Please generate a wave plan first.',
  'migration.labels.migrationStrategy': 'Migration Strategy',
  'migration.messages.generateStrategyFirst': 'Please Generate Migration Strategy First',
  'common.messages.noDataAvailable': 'No data available',
  'migration.messages.selectDatabaseParams': 'Please select database parameters',
  'common.app.title': 'IDMA : Intelligent Data Modernization Assistant',
  'migration.labels.infrastructureAsCode': 'Infrastructure as Code (',
  'migration.messages.generatingRunbook': 'Generating runbook...',
  'analytics.messages.noInputData': 'No input data available. Please provide inputs via form.',
  'migration.messages.generateIaCFirst': 'Please generate infrastructure as code first.',
  'migration.actions.showTimeline': 'Show Timeline',
  'migration.labels.totalEffortsMax': 'Total Efforts (Weeks) - Max: ',
  'common.labels.referencesColon': 'References:',
  'migration.labels.application': 'Application: ',
  'bot.actions.sendFollowup': 'Send Follow-up',
    'analytics.labels.businessUseCase': 'Business Use Case',
    'analytics.labels.sourceTechnology': 'Source Technology',
    'analytics.labels.technicalTrack': 'Technical Track',
    'analytics.labels.inputSummary': 'Input Summary',
    'analytics.messages.generatingStrategy': 'Generating migration strategy...',
    'analytics.actions.generateStrategy': 'Generate Data Strategy',
    'strategy.labels.modernDataStrategy': 'Modern Data Strategy'
  };
  
  return keyToTextMap[key] || key;
};

// For components that need i18next key format
export const useTranslation = () => ({
  t: (key: string) => t(key)
});
